//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorResponseStatus.
const (
	False ErrorResponseStatus = false
)

// Defines values for FileType.
const (
	Dir  FileType = "dir"
	File FileType = "file"
)

// Adapter Storage adapter key
type Adapter = string

// AdapterList List of all available storage adapter keys configured in the system
type AdapterList = []Adapter

// ArchiveName Archive name without extension (pathinfo PATHINFO_FILENAME extracts this, .zip added automatically)
type ArchiveName = string

// ArchiveRequest defines model for ArchiveRequest.
type ArchiveRequest struct {
	// Items Array of items for batch operations
	Items FileItemList `json:"items"`

	// Name Archive name without extension (pathinfo PATHINFO_FILENAME extracts this, .zip added automatically)
	Name ArchiveName `json:"name"`
}

// Basename Base name of the file or directory (extracted via basename() function)
type Basename = string

// CreateRequest Request to create a new file or folder (name validated against \\/?%*:|"<> characters)
type CreateRequest struct {
	// Name Name that must not contain \/?%*:|"<> characters
	Name Name `json:"name"`
}

// DeleteRequest defines model for DeleteRequest.
type DeleteRequest struct {
	// Items Array of items for batch operations
	Items FileItemList `json:"items"`
}

// DirectoryListingResponse Standard response containing directory contents and metadata
type DirectoryListingResponse struct {
	// Adapter Storage adapter key
	Adapter Adapter `json:"adapter"`

	// Dirname Directory path with adapter prefix
	Dirname DirectoryPath `json:"dirname"`

	// Files Array of files and directories (directories listed first, then files)
	Files FileList `json:"files"`

	// Storages List of all available storage adapter keys configured in the system
	Storages AdapterList `json:"storages"`
}

// DirectoryPath Directory path with adapter prefix
type DirectoryPath = string

// ErrorResponse Standard error response returned with 400 status code
type ErrorResponse struct {
	// Message Human-readable error message describing what went wrong
	Message string `json:"message"`

	// Status Always false for error responses
	Status ErrorResponseStatus `json:"status"`
}

// ErrorResponseStatus Always false for error responses
type ErrorResponseStatus bool

// Extension File extension without the dot (extracted via pathinfo)
type Extension = string

// FileContent Text content of a file
type FileContent = string

// FileItem Reference to a file or directory for batch operations (move, delete, archive)
type FileItem struct {
	// Path Full path with adapter prefix
	Path Path `json:"path"`

	// Type Type of the node - 'file' for files, 'dir' for directories
	Type FileType `json:"type"`
}

// FileItemList Array of items for batch operations
type FileItemList = []FileItem

// FileList Array of files and directories (directories listed first, then files)
type FileList = []FileNode

// FileNode Represents a file or directory in the file system
type FileNode struct {
	// Basename Base name of the file or directory (extracted via basename() function)
	Basename Basename `json:"basename"`

	// Dir Directory path with adapter prefix
	Dir *DirectoryPath `json:"dir,omitempty"`

	// Extension File extension without the dot (extracted via pathinfo)
	Extension *Extension `json:"extension,omitempty"`

	// LastModified Unix timestamp
	LastModified *Timestamp `json:"last_modified,omitempty"`

	// MimeType MIME type of the file (detected by filesystem)
	MimeType *MimeType `json:"mime_type,omitempty"`

	// Path Full path with adapter prefix
	Path Path `json:"path"`

	// Size File size in bytes (provided by filesystem StorageAttributes)
	Size *FileSize `json:"size,omitempty"`

	// Storage Storage adapter key
	Storage Adapter `json:"storage"`

	// Type Type of the node - 'file' for files, 'dir' for directories
	Type FileType `json:"type"`

	// Url Public URL to access the file
	Url *Url `json:"url,omitempty"`
}

// FileSize File size in bytes (provided by filesystem StorageAttributes)
type FileSize = int64

// FileType Type of the node - 'file' for files, 'dir' for directories
type FileType string

// Folder Subfolder information for tree navigation
type Folder struct {
	// Adapter Storage adapter key
	Adapter Adapter `json:"adapter"`

	// Basename Base name of the file or directory (extracted via basename() function)
	Basename Basename `json:"basename"`

	// Path Full path with adapter prefix
	Path Path `json:"path"`
}

// FolderList Array of folders
type FolderList = []Folder

// MimeType MIME type of the file (detected by filesystem)
type MimeType = string

// MoveRequest defines model for MoveRequest.
type MoveRequest struct {
	// Item Directory path with adapter prefix
	Item DirectoryPath `json:"item"`

	// Items Array of items for batch operations
	Items FileItemList `json:"items"`
}

// Name Name that must not contain \/?%*:|"<> characters
type Name = string

// Path Full path with adapter prefix
type Path = string

// RenameRequest defines model for RenameRequest.
type RenameRequest struct {
	// Item Full path with adapter prefix
	Item Path `json:"item"`

	// Name Name that must not contain \/?%*:|"<> characters
	Name Name `json:"name"`
}

// SaveRequest defines model for SaveRequest.
type SaveRequest struct {
	// Content Text content of a file
	Content FileContent `json:"content"`
}

// SearchFilter Search filter/pattern (case-insensitive, uses fnmatch with wildcards)
type SearchFilter = string

// SubfoldersResponse defines model for SubfoldersResponse.
type SubfoldersResponse struct {
	// Folders Array of folders
	Folders FolderList `json:"folders"`
}

// Timestamp Unix timestamp
type Timestamp = int64

// UnarchiveRequest defines model for UnarchiveRequest.
type UnarchiveRequest struct {
	// Item Full path with adapter prefix
	Item Path `json:"item"`
}

// UploadSuccessResponse defines model for UploadSuccessResponse.
type UploadSuccessResponse = []string

// Url Public URL to access the file
type Url = string

// DirectoryPathRequired Directory path with adapter prefix
type DirectoryPathRequired = DirectoryPath

// PathParam Directory path with adapter prefix
type PathParam = DirectoryPath

// PathRequired Full path with adapter prefix
type PathRequired = Path

// DirectoryListing Standard response containing directory contents and metadata
type DirectoryListing = DirectoryListingResponse

// Error Standard error response returned with 400 status code
type Error = ErrorResponse

// Subfolders defines model for Subfolders.
type Subfolders = SubfoldersResponse

// UploadSuccess defines model for UploadSuccess.
type UploadSuccess = UploadSuccessResponse

// PostArchiveParams defines parameters for PostArchive.
type PostArchiveParams struct {
	// Adapter Storage adapter key to use. If not provided or invalid, defaults to first configured adapter
	Adapter *Adapter `form:"adapter,omitempty" json:"adapter,omitempty"`

	// Path Directory path
	Path DirectoryPathRequired `form:"path" json:"path"`
}

// PostDeleteParams defines parameters for PostDelete.
type PostDeleteParams struct {
	// Adapter Storage adapter key to use. If not provided or invalid, defaults to first configured adapter
	Adapter *Adapter `form:"adapter,omitempty" json:"adapter,omitempty"`

	// Path Directory path
	Path DirectoryPathRequired `form:"path" json:"path"`
}

// GetDownloadParams defines parameters for GetDownload.
type GetDownloadParams struct {
	// Adapter Storage adapter key to use. If not provided or invalid, defaults to first configured adapter
	Adapter *Adapter `form:"adapter,omitempty" json:"adapter,omitempty"`

	// Path Full path to the file
	Path PathRequired `form:"path" json:"path"`
}

// GetIndexParams defines parameters for GetIndex.
type GetIndexParams struct {
	// Adapter Storage adapter key to use. If not provided or invalid, defaults to first configured adapter
	Adapter *Adapter `form:"adapter,omitempty" json:"adapter,omitempty"`

	// Path Directory or file path with adapter prefix. Defaults to 'adapter://' (root of adapter)
	Path *PathParam `form:"path,omitempty" json:"path,omitempty"`
}

// PostMoveParams defines parameters for PostMove.
type PostMoveParams struct {
	// Adapter Storage adapter key to use. If not provided or invalid, defaults to first configured adapter
	Adapter *Adapter `form:"adapter,omitempty" json:"adapter,omitempty"`

	// Path Directory path
	Path DirectoryPathRequired `form:"path" json:"path"`
}

// PostNewfileParams defines parameters for PostNewfile.
type PostNewfileParams struct {
	// Adapter Storage adapter key to use. If not provided or invalid, defaults to first configured adapter
	Adapter *Adapter `form:"adapter,omitempty" json:"adapter,omitempty"`

	// Path Directory path
	Path DirectoryPathRequired `form:"path" json:"path"`
}

// PostNewfolderParams defines parameters for PostNewfolder.
type PostNewfolderParams struct {
	// Adapter Storage adapter key to use. If not provided or invalid, defaults to first configured adapter
	Adapter *Adapter `form:"adapter,omitempty" json:"adapter,omitempty"`

	// Path Directory path
	Path DirectoryPathRequired `form:"path" json:"path"`
}

// GetPreviewParams defines parameters for GetPreview.
type GetPreviewParams struct {
	// Adapter Storage adapter key to use. If not provided or invalid, defaults to first configured adapter
	Adapter *Adapter `form:"adapter,omitempty" json:"adapter,omitempty"`

	// Path Full path to the file
	Path PathRequired `form:"path" json:"path"`
}

// PostRenameParams defines parameters for PostRename.
type PostRenameParams struct {
	// Adapter Storage adapter key to use. If not provided or invalid, defaults to first configured adapter
	Adapter *Adapter `form:"adapter,omitempty" json:"adapter,omitempty"`

	// Path Directory path
	Path DirectoryPathRequired `form:"path" json:"path"`
}

// PostSaveParams defines parameters for PostSave.
type PostSaveParams struct {
	// Adapter Storage adapter key to use. If not provided or invalid, defaults to first configured adapter
	Adapter *Adapter `form:"adapter,omitempty" json:"adapter,omitempty"`

	// Path Full path to the file
	Path PathRequired `form:"path" json:"path"`
}

// GetSearchParams defines parameters for GetSearch.
type GetSearchParams struct {
	// Adapter Storage adapter key to use. If not provided or invalid, defaults to first configured adapter
	Adapter *Adapter `form:"adapter,omitempty" json:"adapter,omitempty"`

	// Path Directory or file path with adapter prefix. Defaults to 'adapter://' (root of adapter)
	Path *PathParam `form:"path,omitempty" json:"path,omitempty"`

	// Filter Search filter/pattern (case-insensitive, uses fnmatch with wildcards)
	Filter SearchFilter `form:"filter" json:"filter"`
}

// GetSubfoldersParams defines parameters for GetSubfolders.
type GetSubfoldersParams struct {
	// Adapter Storage adapter key to use. If not provided or invalid, defaults to first configured adapter
	Adapter *Adapter `form:"adapter,omitempty" json:"adapter,omitempty"`

	// Path Directory or file path with adapter prefix. Defaults to 'adapter://' (root of adapter)
	Path *PathParam `form:"path,omitempty" json:"path,omitempty"`
}

// PostUnarchiveParams defines parameters for PostUnarchive.
type PostUnarchiveParams struct {
	// Adapter Storage adapter key to use. If not provided or invalid, defaults to first configured adapter
	Adapter *Adapter `form:"adapter,omitempty" json:"adapter,omitempty"`

	// Path Directory path
	Path DirectoryPathRequired `form:"path" json:"path"`
}

// PostUploadMultipartBody defines parameters for PostUpload.
type PostUploadMultipartBody struct {
	// File File data to upload
	File openapi_types.File `json:"file"`

	// Name Target filename (appended to path with DIRECTORY_SEPARATOR)
	Name string `json:"name"`
}

// PostUploadParams defines parameters for PostUpload.
type PostUploadParams struct {
	// Adapter Storage adapter key to use. If not provided or invalid, defaults to first configured adapter
	Adapter *Adapter `form:"adapter,omitempty" json:"adapter,omitempty"`

	// Path Directory path
	Path DirectoryPathRequired `form:"path" json:"path"`
}

// PostArchiveJSONRequestBody defines body for PostArchive for application/json ContentType.
type PostArchiveJSONRequestBody = ArchiveRequest

// PostDeleteJSONRequestBody defines body for PostDelete for application/json ContentType.
type PostDeleteJSONRequestBody = DeleteRequest

// PostMoveJSONRequestBody defines body for PostMove for application/json ContentType.
type PostMoveJSONRequestBody = MoveRequest

// PostNewfileJSONRequestBody defines body for PostNewfile for application/json ContentType.
type PostNewfileJSONRequestBody = CreateRequest

// PostNewfolderJSONRequestBody defines body for PostNewfolder for application/json ContentType.
type PostNewfolderJSONRequestBody = CreateRequest

// PostRenameJSONRequestBody defines body for PostRename for application/json ContentType.
type PostRenameJSONRequestBody = RenameRequest

// PostSaveJSONRequestBody defines body for PostSave for application/json ContentType.
type PostSaveJSONRequestBody = SaveRequest

// PostUnarchiveJSONRequestBody defines body for PostUnarchive for application/json ContentType.
type PostUnarchiveJSONRequestBody = UnarchiveRequest

// PostUploadMultipartRequestBody defines body for PostUpload for multipart/form-data ContentType.
type PostUploadMultipartRequestBody PostUploadMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CORS preflight
	// (OPTIONS /)
	Options(w http.ResponseWriter, r *http.Request)
	// Create archive
	// (POST /archive)
	PostArchive(w http.ResponseWriter, r *http.Request, params PostArchiveParams)
	// Delete files or folders
	// (POST /delete)
	PostDelete(w http.ResponseWriter, r *http.Request, params PostDeleteParams)
	// Download file
	// (GET /download)
	GetDownload(w http.ResponseWriter, r *http.Request, params GetDownloadParams)
	// List directory contents
	// (GET /index)
	GetIndex(w http.ResponseWriter, r *http.Request, params GetIndexParams)
	// Move files or folders
	// (POST /move)
	PostMove(w http.ResponseWriter, r *http.Request, params PostMoveParams)
	// Create new file
	// (POST /newfile)
	PostNewfile(w http.ResponseWriter, r *http.Request, params PostNewfileParams)
	// Create new folder
	// (POST /newfolder)
	PostNewfolder(w http.ResponseWriter, r *http.Request, params PostNewfolderParams)
	// Preview file
	// (GET /preview)
	GetPreview(w http.ResponseWriter, r *http.Request, params GetPreviewParams)
	// Rename file or folder
	// (POST /rename)
	PostRename(w http.ResponseWriter, r *http.Request, params PostRenameParams)
	// Save file content
	// (POST /save)
	PostSave(w http.ResponseWriter, r *http.Request, params PostSaveParams)
	// Search files
	// (GET /search)
	GetSearch(w http.ResponseWriter, r *http.Request, params GetSearchParams)
	// List subfolders
	// (GET /subfolders)
	GetSubfolders(w http.ResponseWriter, r *http.Request, params GetSubfoldersParams)
	// Extract archive
	// (POST /unarchive)
	PostUnarchive(w http.ResponseWriter, r *http.Request, params PostUnarchiveParams)
	// Upload file
	// (POST /upload)
	PostUpload(w http.ResponseWriter, r *http.Request, params PostUploadParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Options operation middleware
func (siw *ServerInterfaceWrapper) Options(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Options(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostArchive operation middleware
func (siw *ServerInterfaceWrapper) PostArchive(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostArchiveParams

	// ------------- Optional query parameter "adapter" -------------

	err = runtime.BindQueryParameter("form", true, false, "adapter", r.URL.Query(), &params.Adapter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adapter", Err: err})
		return
	}

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostArchive(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDelete operation middleware
func (siw *ServerInterfaceWrapper) PostDelete(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDeleteParams

	// ------------- Optional query parameter "adapter" -------------

	err = runtime.BindQueryParameter("form", true, false, "adapter", r.URL.Query(), &params.Adapter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adapter", Err: err})
		return
	}

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDelete(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDownload operation middleware
func (siw *ServerInterfaceWrapper) GetDownload(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDownloadParams

	// ------------- Optional query parameter "adapter" -------------

	err = runtime.BindQueryParameter("form", true, false, "adapter", r.URL.Query(), &params.Adapter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adapter", Err: err})
		return
	}

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDownload(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIndex operation middleware
func (siw *ServerInterfaceWrapper) GetIndex(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetIndexParams

	// ------------- Optional query parameter "adapter" -------------

	err = runtime.BindQueryParameter("form", true, false, "adapter", r.URL.Query(), &params.Adapter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adapter", Err: err})
		return
	}

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, false, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIndex(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostMove operation middleware
func (siw *ServerInterfaceWrapper) PostMove(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostMoveParams

	// ------------- Optional query parameter "adapter" -------------

	err = runtime.BindQueryParameter("form", true, false, "adapter", r.URL.Query(), &params.Adapter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adapter", Err: err})
		return
	}

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostMove(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostNewfile operation middleware
func (siw *ServerInterfaceWrapper) PostNewfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostNewfileParams

	// ------------- Optional query parameter "adapter" -------------

	err = runtime.BindQueryParameter("form", true, false, "adapter", r.URL.Query(), &params.Adapter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adapter", Err: err})
		return
	}

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostNewfile(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostNewfolder operation middleware
func (siw *ServerInterfaceWrapper) PostNewfolder(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostNewfolderParams

	// ------------- Optional query parameter "adapter" -------------

	err = runtime.BindQueryParameter("form", true, false, "adapter", r.URL.Query(), &params.Adapter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adapter", Err: err})
		return
	}

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostNewfolder(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPreview operation middleware
func (siw *ServerInterfaceWrapper) GetPreview(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPreviewParams

	// ------------- Optional query parameter "adapter" -------------

	err = runtime.BindQueryParameter("form", true, false, "adapter", r.URL.Query(), &params.Adapter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adapter", Err: err})
		return
	}

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPreview(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRename operation middleware
func (siw *ServerInterfaceWrapper) PostRename(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostRenameParams

	// ------------- Optional query parameter "adapter" -------------

	err = runtime.BindQueryParameter("form", true, false, "adapter", r.URL.Query(), &params.Adapter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adapter", Err: err})
		return
	}

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRename(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSave operation middleware
func (siw *ServerInterfaceWrapper) PostSave(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostSaveParams

	// ------------- Optional query parameter "adapter" -------------

	err = runtime.BindQueryParameter("form", true, false, "adapter", r.URL.Query(), &params.Adapter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adapter", Err: err})
		return
	}

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSave(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSearch operation middleware
func (siw *ServerInterfaceWrapper) GetSearch(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchParams

	// ------------- Optional query parameter "adapter" -------------

	err = runtime.BindQueryParameter("form", true, false, "adapter", r.URL.Query(), &params.Adapter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adapter", Err: err})
		return
	}

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, false, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	// ------------- Required query parameter "filter" -------------

	if paramValue := r.URL.Query().Get("filter"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "filter"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "filter", r.URL.Query(), &params.Filter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSearch(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubfolders operation middleware
func (siw *ServerInterfaceWrapper) GetSubfolders(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSubfoldersParams

	// ------------- Optional query parameter "adapter" -------------

	err = runtime.BindQueryParameter("form", true, false, "adapter", r.URL.Query(), &params.Adapter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adapter", Err: err})
		return
	}

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, false, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubfolders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUnarchive operation middleware
func (siw *ServerInterfaceWrapper) PostUnarchive(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostUnarchiveParams

	// ------------- Optional query parameter "adapter" -------------

	err = runtime.BindQueryParameter("form", true, false, "adapter", r.URL.Query(), &params.Adapter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adapter", Err: err})
		return
	}

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUnarchive(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUpload operation middleware
func (siw *ServerInterfaceWrapper) PostUpload(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostUploadParams

	// ------------- Optional query parameter "adapter" -------------

	err = runtime.BindQueryParameter("form", true, false, "adapter", r.URL.Query(), &params.Adapter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adapter", Err: err})
		return
	}

	// ------------- Required query parameter "path" -------------

	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUpload(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("OPTIONS "+options.BaseURL+"/{$}", wrapper.Options)
	m.HandleFunc("POST "+options.BaseURL+"/archive", wrapper.PostArchive)
	m.HandleFunc("POST "+options.BaseURL+"/delete", wrapper.PostDelete)
	m.HandleFunc("GET "+options.BaseURL+"/download", wrapper.GetDownload)
	m.HandleFunc("GET "+options.BaseURL+"/index", wrapper.GetIndex)
	m.HandleFunc("POST "+options.BaseURL+"/move", wrapper.PostMove)
	m.HandleFunc("POST "+options.BaseURL+"/newfile", wrapper.PostNewfile)
	m.HandleFunc("POST "+options.BaseURL+"/newfolder", wrapper.PostNewfolder)
	m.HandleFunc("GET "+options.BaseURL+"/preview", wrapper.GetPreview)
	m.HandleFunc("POST "+options.BaseURL+"/rename", wrapper.PostRename)
	m.HandleFunc("POST "+options.BaseURL+"/save", wrapper.PostSave)
	m.HandleFunc("GET "+options.BaseURL+"/search", wrapper.GetSearch)
	m.HandleFunc("GET "+options.BaseURL+"/subfolders", wrapper.GetSubfolders)
	m.HandleFunc("POST "+options.BaseURL+"/unarchive", wrapper.PostUnarchive)
	m.HandleFunc("POST "+options.BaseURL+"/upload", wrapper.PostUpload)

	return m
}
