//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorResponseStatus.
const (
	False ErrorResponseStatus = false
)

// Defines values for NodeType.
const (
	Dir  NodeType = "dir"
	File NodeType = "file"
)

// Defines values for SnapshotType.
const (
	Borg   SnapshotType = "borg"
	Git    SnapshotType = "git"
	Restic SnapshotType = "restic"
	Zfs    SnapshotType = "zfs"
)

// Defines values for GetNodesOrder.
const (
	GetNodesOrderAsc  GetNodesOrder = "asc"
	GetNodesOrderDesc GetNodesOrder = "desc"
)

// Defines values for GetNodesSort.
const (
	GetNodesSortModifiedAt GetNodesSort = "modified_at"
	GetNodesSortName       GetNodesSort = "name"
	GetNodesSortSize       GetNodesSort = "size"
	GetNodesSortType       GetNodesSort = "type"
)

// Defines values for SnapshotsOrder.
const (
	SnapshotsOrderAsc  SnapshotsOrder = "asc"
	SnapshotsOrderDesc SnapshotsOrder = "desc"
)

// Defines values for SnapshotsSort.
const (
	SnapshotsSortName      SnapshotsSort = "name"
	SnapshotsSortSize      SnapshotsSort = "size"
	SnapshotsSortTimestamp SnapshotsSort = "timestamp"
)

// Defines values for GetStoragesStorageNodeSnapshotsParamsSort.
const (
	GetStoragesStorageNodeSnapshotsParamsSortName      GetStoragesStorageNodeSnapshotsParamsSort = "name"
	GetStoragesStorageNodeSnapshotsParamsSortSize      GetStoragesStorageNodeSnapshotsParamsSort = "size"
	GetStoragesStorageNodeSnapshotsParamsSortTimestamp GetStoragesStorageNodeSnapshotsParamsSort = "timestamp"
)

// Defines values for GetStoragesStorageNodeSnapshotsParamsOrder.
const (
	GetStoragesStorageNodeSnapshotsParamsOrderAsc  GetStoragesStorageNodeSnapshotsParamsOrder = "asc"
	GetStoragesStorageNodeSnapshotsParamsOrderDesc GetStoragesStorageNodeSnapshotsParamsOrder = "desc"
)

// Defines values for GetStoragesStorageNodeSnapshotsPathParamsSort.
const (
	GetStoragesStorageNodeSnapshotsPathParamsSortName      GetStoragesStorageNodeSnapshotsPathParamsSort = "name"
	GetStoragesStorageNodeSnapshotsPathParamsSortSize      GetStoragesStorageNodeSnapshotsPathParamsSort = "size"
	GetStoragesStorageNodeSnapshotsPathParamsSortTimestamp GetStoragesStorageNodeSnapshotsPathParamsSort = "timestamp"
)

// Defines values for GetStoragesStorageNodeSnapshotsPathParamsOrder.
const (
	GetStoragesStorageNodeSnapshotsPathParamsOrderAsc  GetStoragesStorageNodeSnapshotsPathParamsOrder = "asc"
	GetStoragesStorageNodeSnapshotsPathParamsOrderDesc GetStoragesStorageNodeSnapshotsPathParamsOrder = "desc"
)

// Defines values for GetStoragesStorageNodesParamsSort.
const (
	GetStoragesStorageNodesParamsSortModifiedAt GetStoragesStorageNodesParamsSort = "modified_at"
	GetStoragesStorageNodesParamsSortName       GetStoragesStorageNodesParamsSort = "name"
	GetStoragesStorageNodesParamsSortSize       GetStoragesStorageNodesParamsSort = "size"
	GetStoragesStorageNodesParamsSortType       GetStoragesStorageNodesParamsSort = "type"
)

// Defines values for GetStoragesStorageNodesParamsOrder.
const (
	GetStoragesStorageNodesParamsOrderAsc  GetStoragesStorageNodesParamsOrder = "asc"
	GetStoragesStorageNodesParamsOrderDesc GetStoragesStorageNodesParamsOrder = "desc"
)

// Defines values for GetStoragesStorageNodesPathParamsSort.
const (
	GetStoragesStorageNodesPathParamsSortModifiedAt GetStoragesStorageNodesPathParamsSort = "modified_at"
	GetStoragesStorageNodesPathParamsSortName       GetStoragesStorageNodesPathParamsSort = "name"
	GetStoragesStorageNodesPathParamsSortSize       GetStoragesStorageNodesPathParamsSort = "size"
	GetStoragesStorageNodesPathParamsSortType       GetStoragesStorageNodesPathParamsSort = "type"
)

// Defines values for GetStoragesStorageNodesPathParamsOrder.
const (
	GetStoragesStorageNodesPathParamsOrderAsc  GetStoragesStorageNodesPathParamsOrder = "asc"
	GetStoragesStorageNodesPathParamsOrderDesc GetStoragesStorageNodesPathParamsOrder = "desc"
)

// Defines values for GetStoragesStorageSnapshotNodesSnapshotParamsSort.
const (
	GetStoragesStorageSnapshotNodesSnapshotParamsSortModifiedAt GetStoragesStorageSnapshotNodesSnapshotParamsSort = "modified_at"
	GetStoragesStorageSnapshotNodesSnapshotParamsSortName       GetStoragesStorageSnapshotNodesSnapshotParamsSort = "name"
	GetStoragesStorageSnapshotNodesSnapshotParamsSortSize       GetStoragesStorageSnapshotNodesSnapshotParamsSort = "size"
	GetStoragesStorageSnapshotNodesSnapshotParamsSortType       GetStoragesStorageSnapshotNodesSnapshotParamsSort = "type"
)

// Defines values for GetStoragesStorageSnapshotNodesSnapshotParamsOrder.
const (
	GetStoragesStorageSnapshotNodesSnapshotParamsOrderAsc  GetStoragesStorageSnapshotNodesSnapshotParamsOrder = "asc"
	GetStoragesStorageSnapshotNodesSnapshotParamsOrderDesc GetStoragesStorageSnapshotNodesSnapshotParamsOrder = "desc"
)

// Defines values for GetStoragesStorageSnapshotNodesSnapshotPathParamsSort.
const (
	GetStoragesStorageSnapshotNodesSnapshotPathParamsSortModifiedAt GetStoragesStorageSnapshotNodesSnapshotPathParamsSort = "modified_at"
	GetStoragesStorageSnapshotNodesSnapshotPathParamsSortName       GetStoragesStorageSnapshotNodesSnapshotPathParamsSort = "name"
	GetStoragesStorageSnapshotNodesSnapshotPathParamsSortSize       GetStoragesStorageSnapshotNodesSnapshotPathParamsSort = "size"
	GetStoragesStorageSnapshotNodesSnapshotPathParamsSortType       GetStoragesStorageSnapshotNodesSnapshotPathParamsSort = "type"
)

// Defines values for GetStoragesStorageSnapshotNodesSnapshotPathParamsOrder.
const (
	GetStoragesStorageSnapshotNodesSnapshotPathParamsOrderAsc  GetStoragesStorageSnapshotNodesSnapshotPathParamsOrder = "asc"
	GetStoragesStorageSnapshotNodesSnapshotPathParamsOrderDesc GetStoragesStorageSnapshotNodesSnapshotPathParamsOrder = "desc"
)

// CreateNodeRequest defines model for CreateNodeRequest.
type CreateNodeRequest struct {
	// Content Initial content (only for files)
	Content *string `json:"content,omitempty"`

	// Name Name of the node to create
	Name string `json:"name"`

	// Type Type of the filesystem node
	Type NodeType `json:"type"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Human-readable error message
	Message string `json:"message"`

	// Status Always false for error responses
	Status ErrorResponseStatus `json:"status"`
}

// ErrorResponseStatus Always false for error responses
type ErrorResponseStatus bool

// Node Unified representation of any filesystem object (file or directory).
// Inspired by Unix inode concept where everything is a node with attributes.
type Node struct {
	// Basename Base name of the node
	Basename string `json:"basename"`

	// Children Child nodes (only present for directories when listing)
	Children *[]Node `json:"children,omitempty"`

	// Dir Parent directory path with adapter prefix
	Dir *string `json:"dir,omitempty"`

	// Extension File extension (only for files)
	Extension *string `json:"extension,omitempty"`

	// FileSize Size in bytes (only for files)
	FileSize *int64 `json:"file_size,omitempty"`

	// LastModified Unix timestamp of last modification
	LastModified *int64 `json:"last_modified,omitempty"`

	// MimeType MIME type (only for files)
	MimeType *string `json:"mime_type,omitempty"`

	// Path Full path with adapter prefix
	Path string `json:"path"`

	// Permissions Node permissions
	Permissions *struct {
		Executable *bool `json:"executable,omitempty"`
		Readable   *bool `json:"readable,omitempty"`
		Writable   *bool `json:"writable,omitempty"`
	} `json:"permissions,omitempty"`

	// Storage Storage adapter identifier
	Storage string `json:"storage"`

	// Type Type of the filesystem node
	Type NodeType `json:"type"`
}

// NodeList Response containing list of nodes
type NodeList struct {
	// Adapter Current storage adapter
	Adapter string `json:"adapter"`

	// Dirname Current directory path with adapter prefix
	Dirname string `json:"dirname"`

	// Files Child nodes
	Files []Node `json:"files"`

	// Path Current directory path without adapter prefix
	Path *string `json:"path,omitempty"`

	// Storage Current storage adapter
	Storage string `json:"storage"`

	// Storages Available storage adapters
	Storages []string `json:"storages"`
}

// NodeSnapshotsList Response for node-snapshots endpoint.
// Lists all snapshots available for a specific node.
type NodeSnapshotsList struct {
	// AvailableTypes Available snapshot types for this storage
	AvailableTypes *[]SnapshotType `json:"available_types,omitempty"`

	// Path Path of the node (relative to storage root, empty string for root)
	Path string `json:"path"`

	// Snapshots List of snapshots for this node, ordered by timestamp (newest first by default)
	Snapshots []Snapshot `json:"snapshots"`

	// Storage Storage adapter identifier
	Storage string `json:"storage"`
}

// NodeType Type of the filesystem node
type NodeType string

// Snapshot Point-in-time snapshot of a file or directory.
// Snapshot ID format: "type:backend-id" (e.g., "zfs:tank@daily-2024-10-28")
type Snapshot struct {
	// Id Unique identifier for this snapshot in format "type:backend-id"
	// Used in snapshot-nodes endpoint to reference this snapshot
	Id string `json:"id"`

	// Metadata Backend-specific metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Name Human-readable name/label for snapshot
	Name *string `json:"name,omitempty"`

	// Size Size of the node in this snapshot (file size or directory size)
	Size *int64 `json:"size,omitempty"`

	// Timestamp Unix timestamp when snapshot was created
	Timestamp int64 `json:"timestamp"`

	// Type Snapshot backend type
	Type SnapshotType `json:"type"`
}

// SnapshotType Snapshot backend type
type SnapshotType string

// UpdateNodeRequest defines model for UpdateNodeRequest.
type UpdateNodeRequest struct {
	// Content Updated content (only for files)
	Content *string `json:"content,omitempty"`

	// Name New name for the node (rename)
	Name *string `json:"name,omitempty"`
}

// DeleteNodesRecursive defines model for deleteNodesRecursive.
type DeleteNodesRecursive = bool

// GetNodesChildren defines model for getNodesChildren.
type GetNodesChildren = bool

// GetNodesDownload defines model for getNodesDownload.
type GetNodesDownload = bool

// GetNodesFilter defines model for getNodesFilter.
type GetNodesFilter = string

// GetNodesOrder defines model for getNodesOrder.
type GetNodesOrder string

// GetNodesSearch defines model for getNodesSearch.
type GetNodesSearch = string

// GetNodesSort defines model for getNodesSort.
type GetNodesSort string

// GetNodesType Type of the filesystem node
type GetNodesType = NodeType

// NodePath defines model for nodePath.
type NodePath = string

// SnapshotsLimit defines model for snapshotsLimit.
type SnapshotsLimit = int

// SnapshotsOffset defines model for snapshotsOffset.
type SnapshotsOffset = int

// SnapshotsOrder defines model for snapshotsOrder.
type SnapshotsOrder string

// SnapshotsSort defines model for snapshotsSort.
type SnapshotsSort string

// SnapshotsType Snapshot backend type
type SnapshotsType = SnapshotType

// Storage defines model for storage.
type Storage = string

// BadRequest400 defines model for badRequest400.
type BadRequest400 = ErrorResponse

// NodeConflict409 defines model for nodeConflict409.
type NodeConflict409 = ErrorResponse

// NodeCreated201 Unified representation of any filesystem object (file or directory).
// Inspired by Unix inode concept where everything is a node with attributes.
type NodeCreated201 = Node

// NodeNotFound404 defines model for nodeNotFound404.
type NodeNotFound404 = ErrorResponse

// NodeSuccess200 defines model for nodeSuccess200.
type NodeSuccess200 struct {
	union json.RawMessage
}

// GetStoragesStorageArchivesParams defines parameters for GetStoragesStorageArchives.
type GetStoragesStorageArchivesParams struct {
	// Path Directory to search (searches recursively)
	Path *string `form:"path,omitempty" json:"path,omitempty"`
}

// PostStoragesStorageArchivesJSONBody defines parameters for PostStoragesStorageArchives.
type PostStoragesStorageArchivesJSONBody struct {
	// Items Nodes to include in archive
	Items []struct {
		Path string `json:"path"`

		// Type Type of the filesystem node
		Type *NodeType `json:"type,omitempty"`
	} `json:"items"`

	// Name Archive name (without .zip extension)
	Name string `json:"name"`
}

// PostStoragesStorageArchivesParams defines parameters for PostStoragesStorageArchives.
type PostStoragesStorageArchivesParams struct {
	// Path Destination directory for archive (defaults to storage root)
	Path *string `form:"path,omitempty" json:"path,omitempty"`
}

// PostStoragesStorageArchivesPathJSONBody defines parameters for PostStoragesStorageArchivesPath.
type PostStoragesStorageArchivesPathJSONBody struct {
	// Destination Destination path (defaults to archive's directory)
	Destination *string `json:"destination,omitempty"`
}

// PostStoragesStorageCopiesJSONBody defines parameters for PostStoragesStorageCopies.
type PostStoragesStorageCopiesJSONBody struct {
	// Destination Destination path
	Destination string `json:"destination"`
	Items       []struct {
		Path string `json:"path"`

		// Type Type of the filesystem node
		Type *NodeType `json:"type,omitempty"`
	} `json:"items"`
}

// PostStoragesStorageMovesJSONBody defines parameters for PostStoragesStorageMoves.
type PostStoragesStorageMovesJSONBody struct {
	// Destination Destination path (relative to storage root)
	Destination string `json:"destination"`

	// Items Nodes to move
	Items []struct {
		// Path Source path
		Path string `json:"path"`

		// Type Type of the filesystem node
		Type *NodeType `json:"type,omitempty"`
	} `json:"items"`
}

// GetStoragesStorageNodeSnapshotsParams defines parameters for GetStoragesStorageNodeSnapshots.
type GetStoragesStorageNodeSnapshotsParams struct {
	// Type Filter snapshots by type (optional, can repeat for multiple types)
	Type *SnapshotsType `form:"type,omitempty" json:"type,omitempty"`

	// Limit Maximum snapshots to return
	Limit *SnapshotsLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset
	Offset *SnapshotsOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Sort Sort field for results
	Sort *GetStoragesStorageNodeSnapshotsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Order Sort order
	Order *GetStoragesStorageNodeSnapshotsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// GetStoragesStorageNodeSnapshotsParamsSort defines parameters for GetStoragesStorageNodeSnapshots.
type GetStoragesStorageNodeSnapshotsParamsSort string

// GetStoragesStorageNodeSnapshotsParamsOrder defines parameters for GetStoragesStorageNodeSnapshots.
type GetStoragesStorageNodeSnapshotsParamsOrder string

// GetStoragesStorageNodeSnapshotsPathParams defines parameters for GetStoragesStorageNodeSnapshotsPath.
type GetStoragesStorageNodeSnapshotsPathParams struct {
	// Type Filter snapshots by type (optional, can repeat for multiple types)
	Type *SnapshotsType `form:"type,omitempty" json:"type,omitempty"`

	// Limit Maximum snapshots to return
	Limit *SnapshotsLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset
	Offset *SnapshotsOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Sort Sort field for results
	Sort *GetStoragesStorageNodeSnapshotsPathParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Order Sort order
	Order *GetStoragesStorageNodeSnapshotsPathParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// GetStoragesStorageNodeSnapshotsPathParamsSort defines parameters for GetStoragesStorageNodeSnapshotsPath.
type GetStoragesStorageNodeSnapshotsPathParamsSort string

// GetStoragesStorageNodeSnapshotsPathParamsOrder defines parameters for GetStoragesStorageNodeSnapshotsPath.
type GetStoragesStorageNodeSnapshotsPathParamsOrder string

// GetStoragesStorageNodesParams defines parameters for GetStoragesStorageNodes.
type GetStoragesStorageNodesParams struct {
	// Type Filter children by type (for directories)
	Type *GetNodesType `form:"type,omitempty" json:"type,omitempty"`

	// Filter Filename pattern (glob-style, e.g., *.pdf)
	Filter *GetNodesFilter `form:"filter,omitempty" json:"filter,omitempty"`

	// Search Search query - searches recursively from this path
	Search *GetNodesSearch `form:"search,omitempty" json:"search,omitempty"`

	// Children Include children in response (for directories)
	Children *GetNodesChildren `form:"children,omitempty" json:"children,omitempty"`

	// Download Set Content-Disposition to attachment (for files)
	Download *GetNodesDownload `form:"download,omitempty" json:"download,omitempty"`

	// Sort Sort field for children
	Sort *GetStoragesStorageNodesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Order Sort order
	Order *GetStoragesStorageNodesParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// GetStoragesStorageNodesParamsSort defines parameters for GetStoragesStorageNodes.
type GetStoragesStorageNodesParamsSort string

// GetStoragesStorageNodesParamsOrder defines parameters for GetStoragesStorageNodes.
type GetStoragesStorageNodesParamsOrder string

// PostStoragesStorageNodesMultipartBody defines parameters for PostStoragesStorageNodes.
type PostStoragesStorageNodesMultipartBody struct {
	// File File to upload
	File openapi_types.File `json:"file"`

	// Name Optional custom filename (defaults to uploaded filename)
	Name *string `json:"name,omitempty"`
}

// DeleteStoragesStorageNodesPathParams defines parameters for DeleteStoragesStorageNodesPath.
type DeleteStoragesStorageNodesPathParams struct {
	// Recursive Delete recursively (for directories)
	Recursive *DeleteNodesRecursive `form:"recursive,omitempty" json:"recursive,omitempty"`
}

// GetStoragesStorageNodesPathParams defines parameters for GetStoragesStorageNodesPath.
type GetStoragesStorageNodesPathParams struct {
	// Type Filter children by type (for directories)
	Type *GetNodesType `form:"type,omitempty" json:"type,omitempty"`

	// Filter Filename pattern (glob-style, e.g., *.pdf)
	Filter *GetNodesFilter `form:"filter,omitempty" json:"filter,omitempty"`

	// Search Search query - searches recursively from this path
	Search *GetNodesSearch `form:"search,omitempty" json:"search,omitempty"`

	// Children Include children in response (for directories)
	Children *GetNodesChildren `form:"children,omitempty" json:"children,omitempty"`

	// Download Set Content-Disposition to attachment (for files)
	Download *GetNodesDownload `form:"download,omitempty" json:"download,omitempty"`

	// Sort Sort field for children
	Sort *GetStoragesStorageNodesPathParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Order Sort order
	Order *GetStoragesStorageNodesPathParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// GetStoragesStorageNodesPathParamsSort defines parameters for GetStoragesStorageNodesPath.
type GetStoragesStorageNodesPathParamsSort string

// GetStoragesStorageNodesPathParamsOrder defines parameters for GetStoragesStorageNodesPath.
type GetStoragesStorageNodesPathParamsOrder string

// PostStoragesStorageNodesPathMultipartBody defines parameters for PostStoragesStorageNodesPath.
type PostStoragesStorageNodesPathMultipartBody struct {
	// File File to upload
	File openapi_types.File `json:"file"`

	// Name Optional custom filename (defaults to uploaded filename)
	Name *string `json:"name,omitempty"`
}

// GetStoragesStorageSnapshotNodesSnapshotParams defines parameters for GetStoragesStorageSnapshotNodesSnapshot.
type GetStoragesStorageSnapshotNodesSnapshotParams struct {
	// Type Filter children by type (for directories)
	Type *GetNodesType `form:"type,omitempty" json:"type,omitempty"`

	// Filter Filename pattern (glob-style, e.g., *.pdf)
	Filter *GetNodesFilter `form:"filter,omitempty" json:"filter,omitempty"`

	// Children Include children in response (for directories)
	Children *GetNodesChildren `form:"children,omitempty" json:"children,omitempty"`

	// Sort Sort field for children
	Sort *GetStoragesStorageSnapshotNodesSnapshotParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Order Sort order
	Order *GetStoragesStorageSnapshotNodesSnapshotParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// GetStoragesStorageSnapshotNodesSnapshotParamsSort defines parameters for GetStoragesStorageSnapshotNodesSnapshot.
type GetStoragesStorageSnapshotNodesSnapshotParamsSort string

// GetStoragesStorageSnapshotNodesSnapshotParamsOrder defines parameters for GetStoragesStorageSnapshotNodesSnapshot.
type GetStoragesStorageSnapshotNodesSnapshotParamsOrder string

// GetStoragesStorageSnapshotNodesSnapshotPathParams defines parameters for GetStoragesStorageSnapshotNodesSnapshotPath.
type GetStoragesStorageSnapshotNodesSnapshotPathParams struct {
	// Type Filter children by type (for directories)
	Type *GetNodesType `form:"type,omitempty" json:"type,omitempty"`

	// Filter Filename pattern (glob-style, e.g., *.pdf)
	Filter *GetNodesFilter `form:"filter,omitempty" json:"filter,omitempty"`

	// Search Search query - searches recursively from this path
	Search *GetNodesSearch `form:"search,omitempty" json:"search,omitempty"`

	// Children Include children in response (for directories)
	Children *GetNodesChildren `form:"children,omitempty" json:"children,omitempty"`

	// Download Set Content-Disposition to attachment (for files)
	Download *GetNodesDownload `form:"download,omitempty" json:"download,omitempty"`

	// Sort Sort field for children
	Sort *GetStoragesStorageSnapshotNodesSnapshotPathParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Order Sort order
	Order *GetStoragesStorageSnapshotNodesSnapshotPathParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// GetStoragesStorageSnapshotNodesSnapshotPathParamsSort defines parameters for GetStoragesStorageSnapshotNodesSnapshotPath.
type GetStoragesStorageSnapshotNodesSnapshotPathParamsSort string

// GetStoragesStorageSnapshotNodesSnapshotPathParamsOrder defines parameters for GetStoragesStorageSnapshotNodesSnapshotPath.
type GetStoragesStorageSnapshotNodesSnapshotPathParamsOrder string

// PostStoragesStorageArchivesJSONRequestBody defines body for PostStoragesStorageArchives for application/json ContentType.
type PostStoragesStorageArchivesJSONRequestBody PostStoragesStorageArchivesJSONBody

// PostStoragesStorageArchivesPathJSONRequestBody defines body for PostStoragesStorageArchivesPath for application/json ContentType.
type PostStoragesStorageArchivesPathJSONRequestBody PostStoragesStorageArchivesPathJSONBody

// PostStoragesStorageCopiesJSONRequestBody defines body for PostStoragesStorageCopies for application/json ContentType.
type PostStoragesStorageCopiesJSONRequestBody PostStoragesStorageCopiesJSONBody

// PostStoragesStorageMovesJSONRequestBody defines body for PostStoragesStorageMoves for application/json ContentType.
type PostStoragesStorageMovesJSONRequestBody PostStoragesStorageMovesJSONBody

// PostStoragesStorageNodesJSONRequestBody defines body for PostStoragesStorageNodes for application/json ContentType.
type PostStoragesStorageNodesJSONRequestBody = CreateNodeRequest

// PostStoragesStorageNodesMultipartRequestBody defines body for PostStoragesStorageNodes for multipart/form-data ContentType.
type PostStoragesStorageNodesMultipartRequestBody PostStoragesStorageNodesMultipartBody

// PatchStoragesStorageNodesPathJSONRequestBody defines body for PatchStoragesStorageNodesPath for application/json ContentType.
type PatchStoragesStorageNodesPathJSONRequestBody = UpdateNodeRequest

// PostStoragesStorageNodesPathJSONRequestBody defines body for PostStoragesStorageNodesPath for application/json ContentType.
type PostStoragesStorageNodesPathJSONRequestBody = CreateNodeRequest

// PostStoragesStorageNodesPathMultipartRequestBody defines body for PostStoragesStorageNodesPath for multipart/form-data ContentType.
type PostStoragesStorageNodesPathMultipartRequestBody PostStoragesStorageNodesPathMultipartBody

// AsNode returns the union data inside the NodeSuccess200 as a Node
func (t NodeSuccess200) AsNode() (Node, error) {
	var body Node
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNode overwrites any union data inside the NodeSuccess200 as the provided Node
func (t *NodeSuccess200) FromNode(v Node) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNode performs a merge with any union data inside the NodeSuccess200, using the provided Node
func (t *NodeSuccess200) MergeNode(v Node) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNodeList returns the union data inside the NodeSuccess200 as a NodeList
func (t NodeSuccess200) AsNodeList() (NodeList, error) {
	var body NodeList
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNodeList overwrites any union data inside the NodeSuccess200 as the provided NodeList
func (t *NodeSuccess200) FromNodeList(v NodeList) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNodeList performs a merge with any union data inside the NodeSuccess200, using the provided NodeList
func (t *NodeSuccess200) MergeNodeList(v NodeList) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NodeSuccess200) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NodeSuccess200) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List available storage backends
	// (GET /storages)
	GetStorages(w http.ResponseWriter, r *http.Request)
	// List all archives
	// (GET /storages/{storage}/archives)
	GetStoragesStorageArchives(w http.ResponseWriter, r *http.Request, storage Storage, params GetStoragesStorageArchivesParams)
	// Create a ZIP archive from nodes
	// (POST /storages/{storage}/archives)
	PostStoragesStorageArchives(w http.ResponseWriter, r *http.Request, storage Storage, params PostStoragesStorageArchivesParams)
	// Extract a ZIP archive
	// (POST /storages/{storage}/archives/{path})
	PostStoragesStorageArchivesPath(w http.ResponseWriter, r *http.Request, storage Storage, path string)
	// Copy nodes to a new location
	// (POST /storages/{storage}/copies)
	PostStoragesStorageCopies(w http.ResponseWriter, r *http.Request, storage Storage)
	// Move nodes to a new location
	// (POST /storages/{storage}/moves)
	PostStoragesStorageMoves(w http.ResponseWriter, r *http.Request, storage Storage)
	// Get snapshots at storage root
	// (GET /storages/{storage}/node-snapshots)
	GetStoragesStorageNodeSnapshots(w http.ResponseWriter, r *http.Request, storage Storage, params GetStoragesStorageNodeSnapshotsParams)
	// Get snapshots for a node
	// (GET /storages/{storage}/node-snapshots/{path...})
	GetStoragesStorageNodeSnapshotsPath(w http.ResponseWriter, r *http.Request, storage Storage, path string, params GetStoragesStorageNodeSnapshotsPathParams)
	// Get storage root information or content
	// (GET /storages/{storage}/nodes)
	GetStoragesStorageNodes(w http.ResponseWriter, r *http.Request, storage Storage, params GetStoragesStorageNodesParams)
	// Create a new child node at storage root
	// (POST /storages/{storage}/nodes)
	PostStoragesStorageNodes(w http.ResponseWriter, r *http.Request, storage Storage)
	// Delete a node
	// (DELETE /storages/{storage}/nodes/{path...})
	DeleteStoragesStorageNodesPath(w http.ResponseWriter, r *http.Request, storage Storage, path NodePath, params DeleteStoragesStorageNodesPathParams)
	// Get node information or content
	// (GET /storages/{storage}/nodes/{path...})
	GetStoragesStorageNodesPath(w http.ResponseWriter, r *http.Request, storage Storage, path NodePath, params GetStoragesStorageNodesPathParams)
	// Update node metadata or content
	// (PATCH /storages/{storage}/nodes/{path...})
	PatchStoragesStorageNodesPath(w http.ResponseWriter, r *http.Request, storage Storage, path NodePath)
	// Create a new child node
	// (POST /storages/{storage}/nodes/{path...})
	PostStoragesStorageNodesPath(w http.ResponseWriter, r *http.Request, storage Storage, path NodePath)
	// Get storage root as it was in a snapshot
	// (GET /storages/{storage}/snapshot-nodes/{snapshot})
	GetStoragesStorageSnapshotNodesSnapshot(w http.ResponseWriter, r *http.Request, storage Storage, snapshot string, params GetStoragesStorageSnapshotNodesSnapshotParams)
	// Get node as it was in a snapshot
	// (GET /storages/{storage}/snapshot-nodes/{snapshot}/{path...})
	GetStoragesStorageSnapshotNodesSnapshotPath(w http.ResponseWriter, r *http.Request, storage Storage, snapshot string, path string, params GetStoragesStorageSnapshotNodesSnapshotPathParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetStorages operation middleware
func (siw *ServerInterfaceWrapper) GetStorages(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStorages(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStoragesStorageArchives operation middleware
func (siw *ServerInterfaceWrapper) GetStoragesStorageArchives(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storage" -------------
	var storage Storage

	err = runtime.BindStyledParameterWithOptions("simple", "storage", r.PathValue("storage"), &storage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storage", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStoragesStorageArchivesParams

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, false, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStoragesStorageArchives(w, r, storage, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostStoragesStorageArchives operation middleware
func (siw *ServerInterfaceWrapper) PostStoragesStorageArchives(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storage" -------------
	var storage Storage

	err = runtime.BindStyledParameterWithOptions("simple", "storage", r.PathValue("storage"), &storage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storage", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PostStoragesStorageArchivesParams

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, false, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostStoragesStorageArchives(w, r, storage, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostStoragesStorageArchivesPath operation middleware
func (siw *ServerInterfaceWrapper) PostStoragesStorageArchivesPath(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storage" -------------
	var storage Storage

	err = runtime.BindStyledParameterWithOptions("simple", "storage", r.PathValue("storage"), &storage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storage", Err: err})
		return
	}

	// ------------- Path parameter "path" -------------
	var path string

	err = runtime.BindStyledParameterWithOptions("simple", "path", r.PathValue("path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostStoragesStorageArchivesPath(w, r, storage, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostStoragesStorageCopies operation middleware
func (siw *ServerInterfaceWrapper) PostStoragesStorageCopies(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storage" -------------
	var storage Storage

	err = runtime.BindStyledParameterWithOptions("simple", "storage", r.PathValue("storage"), &storage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostStoragesStorageCopies(w, r, storage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostStoragesStorageMoves operation middleware
func (siw *ServerInterfaceWrapper) PostStoragesStorageMoves(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storage" -------------
	var storage Storage

	err = runtime.BindStyledParameterWithOptions("simple", "storage", r.PathValue("storage"), &storage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostStoragesStorageMoves(w, r, storage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStoragesStorageNodeSnapshots operation middleware
func (siw *ServerInterfaceWrapper) GetStoragesStorageNodeSnapshots(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storage" -------------
	var storage Storage

	err = runtime.BindStyledParameterWithOptions("simple", "storage", r.PathValue("storage"), &storage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storage", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStoragesStorageNodeSnapshotsParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStoragesStorageNodeSnapshots(w, r, storage, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStoragesStorageNodeSnapshotsPath operation middleware
func (siw *ServerInterfaceWrapper) GetStoragesStorageNodeSnapshotsPath(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storage" -------------
	var storage Storage

	err = runtime.BindStyledParameterWithOptions("simple", "storage", r.PathValue("storage"), &storage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storage", Err: err})
		return
	}

	// ------------- Path parameter "path..." -------------
	var path string

	err = runtime.BindStyledParameterWithOptions("simple", "path", r.PathValue("path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path...", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStoragesStorageNodeSnapshotsPathParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStoragesStorageNodeSnapshotsPath(w, r, storage, path, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStoragesStorageNodes operation middleware
func (siw *ServerInterfaceWrapper) GetStoragesStorageNodes(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storage" -------------
	var storage Storage

	err = runtime.BindStyledParameterWithOptions("simple", "storage", r.PathValue("storage"), &storage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storage", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStoragesStorageNodesParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameter("form", true, false, "filter", r.URL.Query(), &params.Filter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", r.URL.Query(), &params.Search)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "children" -------------

	err = runtime.BindQueryParameter("form", true, false, "children", r.URL.Query(), &params.Children)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "children", Err: err})
		return
	}

	// ------------- Optional query parameter "download" -------------

	err = runtime.BindQueryParameter("form", true, false, "download", r.URL.Query(), &params.Download)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "download", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStoragesStorageNodes(w, r, storage, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostStoragesStorageNodes operation middleware
func (siw *ServerInterfaceWrapper) PostStoragesStorageNodes(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storage" -------------
	var storage Storage

	err = runtime.BindStyledParameterWithOptions("simple", "storage", r.PathValue("storage"), &storage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostStoragesStorageNodes(w, r, storage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteStoragesStorageNodesPath operation middleware
func (siw *ServerInterfaceWrapper) DeleteStoragesStorageNodesPath(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storage" -------------
	var storage Storage

	err = runtime.BindStyledParameterWithOptions("simple", "storage", r.PathValue("storage"), &storage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storage", Err: err})
		return
	}

	// ------------- Path parameter "path..." -------------
	var path NodePath

	err = runtime.BindStyledParameterWithOptions("simple", "path", r.PathValue("path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path...", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteStoragesStorageNodesPathParams

	// ------------- Optional query parameter "recursive" -------------

	err = runtime.BindQueryParameter("form", true, false, "recursive", r.URL.Query(), &params.Recursive)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recursive", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteStoragesStorageNodesPath(w, r, storage, path, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStoragesStorageNodesPath operation middleware
func (siw *ServerInterfaceWrapper) GetStoragesStorageNodesPath(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storage" -------------
	var storage Storage

	err = runtime.BindStyledParameterWithOptions("simple", "storage", r.PathValue("storage"), &storage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storage", Err: err})
		return
	}

	// ------------- Path parameter "path..." -------------
	var path NodePath

	err = runtime.BindStyledParameterWithOptions("simple", "path", r.PathValue("path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path...", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStoragesStorageNodesPathParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameter("form", true, false, "filter", r.URL.Query(), &params.Filter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", r.URL.Query(), &params.Search)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "children" -------------

	err = runtime.BindQueryParameter("form", true, false, "children", r.URL.Query(), &params.Children)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "children", Err: err})
		return
	}

	// ------------- Optional query parameter "download" -------------

	err = runtime.BindQueryParameter("form", true, false, "download", r.URL.Query(), &params.Download)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "download", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStoragesStorageNodesPath(w, r, storage, path, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchStoragesStorageNodesPath operation middleware
func (siw *ServerInterfaceWrapper) PatchStoragesStorageNodesPath(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storage" -------------
	var storage Storage

	err = runtime.BindStyledParameterWithOptions("simple", "storage", r.PathValue("storage"), &storage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storage", Err: err})
		return
	}

	// ------------- Path parameter "path..." -------------
	var path NodePath

	err = runtime.BindStyledParameterWithOptions("simple", "path", r.PathValue("path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path...", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchStoragesStorageNodesPath(w, r, storage, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostStoragesStorageNodesPath operation middleware
func (siw *ServerInterfaceWrapper) PostStoragesStorageNodesPath(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storage" -------------
	var storage Storage

	err = runtime.BindStyledParameterWithOptions("simple", "storage", r.PathValue("storage"), &storage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storage", Err: err})
		return
	}

	// ------------- Path parameter "path..." -------------
	var path NodePath

	err = runtime.BindStyledParameterWithOptions("simple", "path", r.PathValue("path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path...", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostStoragesStorageNodesPath(w, r, storage, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStoragesStorageSnapshotNodesSnapshot operation middleware
func (siw *ServerInterfaceWrapper) GetStoragesStorageSnapshotNodesSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storage" -------------
	var storage Storage

	err = runtime.BindStyledParameterWithOptions("simple", "storage", r.PathValue("storage"), &storage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storage", Err: err})
		return
	}

	// ------------- Path parameter "snapshot" -------------
	var snapshot string

	err = runtime.BindStyledParameterWithOptions("simple", "snapshot", r.PathValue("snapshot"), &snapshot, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "snapshot", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStoragesStorageSnapshotNodesSnapshotParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameter("form", true, false, "filter", r.URL.Query(), &params.Filter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		return
	}

	// ------------- Optional query parameter "children" -------------

	err = runtime.BindQueryParameter("form", true, false, "children", r.URL.Query(), &params.Children)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "children", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStoragesStorageSnapshotNodesSnapshot(w, r, storage, snapshot, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStoragesStorageSnapshotNodesSnapshotPath operation middleware
func (siw *ServerInterfaceWrapper) GetStoragesStorageSnapshotNodesSnapshotPath(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storage" -------------
	var storage Storage

	err = runtime.BindStyledParameterWithOptions("simple", "storage", r.PathValue("storage"), &storage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storage", Err: err})
		return
	}

	// ------------- Path parameter "snapshot" -------------
	var snapshot string

	err = runtime.BindStyledParameterWithOptions("simple", "snapshot", r.PathValue("snapshot"), &snapshot, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "snapshot", Err: err})
		return
	}

	// ------------- Path parameter "path..." -------------
	var path string

	err = runtime.BindStyledParameterWithOptions("simple", "path", r.PathValue("path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path...", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStoragesStorageSnapshotNodesSnapshotPathParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameter("form", true, false, "filter", r.URL.Query(), &params.Filter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", r.URL.Query(), &params.Search)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "children" -------------

	err = runtime.BindQueryParameter("form", true, false, "children", r.URL.Query(), &params.Children)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "children", Err: err})
		return
	}

	// ------------- Optional query parameter "download" -------------

	err = runtime.BindQueryParameter("form", true, false, "download", r.URL.Query(), &params.Download)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "download", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStoragesStorageSnapshotNodesSnapshotPath(w, r, storage, snapshot, path, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/storages", wrapper.GetStorages)
	m.HandleFunc("GET "+options.BaseURL+"/storages/{storage}/archives", wrapper.GetStoragesStorageArchives)
	m.HandleFunc("POST "+options.BaseURL+"/storages/{storage}/archives", wrapper.PostStoragesStorageArchives)
	m.HandleFunc("POST "+options.BaseURL+"/storages/{storage}/archives/{path}", wrapper.PostStoragesStorageArchivesPath)
	m.HandleFunc("POST "+options.BaseURL+"/storages/{storage}/copies", wrapper.PostStoragesStorageCopies)
	m.HandleFunc("POST "+options.BaseURL+"/storages/{storage}/moves", wrapper.PostStoragesStorageMoves)
	m.HandleFunc("GET "+options.BaseURL+"/storages/{storage}/node-snapshots", wrapper.GetStoragesStorageNodeSnapshots)
	m.HandleFunc("GET "+options.BaseURL+"/storages/{storage}/node-snapshots/{path...}", wrapper.GetStoragesStorageNodeSnapshotsPath)
	m.HandleFunc("GET "+options.BaseURL+"/storages/{storage}/nodes", wrapper.GetStoragesStorageNodes)
	m.HandleFunc("POST "+options.BaseURL+"/storages/{storage}/nodes", wrapper.PostStoragesStorageNodes)
	m.HandleFunc("DELETE "+options.BaseURL+"/storages/{storage}/nodes/{path...}", wrapper.DeleteStoragesStorageNodesPath)
	m.HandleFunc("GET "+options.BaseURL+"/storages/{storage}/nodes/{path...}", wrapper.GetStoragesStorageNodesPath)
	m.HandleFunc("PATCH "+options.BaseURL+"/storages/{storage}/nodes/{path...}", wrapper.PatchStoragesStorageNodesPath)
	m.HandleFunc("POST "+options.BaseURL+"/storages/{storage}/nodes/{path...}", wrapper.PostStoragesStorageNodesPath)
	m.HandleFunc("GET "+options.BaseURL+"/storages/{storage}/snapshot-nodes/{snapshot}", wrapper.GetStoragesStorageSnapshotNodesSnapshot)
	m.HandleFunc("GET "+options.BaseURL+"/storages/{storage}/snapshot-nodes/{snapshot}/{path...}", wrapper.GetStoragesStorageSnapshotNodesSnapshotPath)

	return m
}
