# Commands to build, run, and package the app
#
# See https://taskfile.dev/ for instructions on how to use Taskfile.yml
#
# Run `task` to see the list of tasks
version: '3'

vars:
  BINARY_NAME: timeship
  DOCKER_REPO: ghcr.io/smilyorg/timeship
  DOCKER_REPO_LOCAL: localhost:5000/timeship
  BUILD_OS_ARCH:
    - darwin/amd64
    - darwin/arm64
    - linux/386
    - linux/amd64
    - linux/arm
    - linux/arm64
    - linux/loong64
    - linux/ppc64le
    - linux/riscv64
    - linux/s390x
    - openbsd/amd64
    - openbsd/arm64
    - windows/386
    - windows/amd64
    - windows/arm64
  DOCKER_ARCH:
    - linux/amd64
    - linux/arm64
  DOCKER_ANNOTATIONS: >-
    --annotation 'index:org.opencontainers.image.source=https://github.com/smilyorg/timeship'
    --annotation 'index:org.opencontainers.image.description=ZFS snapshot browser and time machine'
    --annotation 'index:org.opencontainers.image.licenses=MIT'
  VERSION:
    sh: git describe --tags --match "v*" --always --dirty

tasks:
  default:
    cmds:
      - task --list
      - echo ""
      - echo "Common tasks:"
      - "echo '  task dev: Run the API and UI in watch mode'"
      - "echo '  task api: Run the API in watch mode'"
      - "echo '  task ui: Run the UI in watch mode'"
    silent: true

  check:
    desc: Check that dependencies and generated files are up to date
    cmds:
      - task: tidy
      - git diff --exit-code api/go.mod api/go.sum
      - task: gen
      - git diff --exit-code

  tidy:
    desc: Tidy go.mod and go.sum
    dir: api
    cmds:
      - go mod tidy

  gen:
    desc: Generate code from OpenAPI spec
    dir: api
    cmds:
      - go generate -x

  deps:
    desc: Build UI frontend
    deps:
      - build:ui
      - deps:mod

  deps:mod:
    desc: Install Go module dependencies
    dir: api
    cmds:
      - go mod download

  build:ui:
    desc: Build the UI frontend
    dir: ui
    cmds:
      - npm install
      - npm run build -- --clearScreen=false -l warn
      - mkdir -p ../api/ui
      - rm -rf ../api/ui/dist
      - cp -r dist ../api/ui/dist

  build:api:
    desc: Build the API
    dir: api
    sources:
      - '**/*.go'
      - 'go.mod'
      - '**/*.yaml'
    cmds:
      - go build

  run:api:
    desc: Run the API
    dir: api
    cmds:
      - ./timeship

  run:
    desc: Run the API with embedded UI
    deps:
      - build:ui
    dir: api
    env:
      TIMESHIP_API_PREFIX: /api
    cmds:
      - go build -tags embedui
      - ./timeship

  build:run:api:
    desc: Build and run the API
    dir: api
    cmds:
      - task: build:api
      - task: run:api

  dev:
    desc: Run the API and UI in watch mode
    deps:
      - ui
      - api

  ui:
    desc: Run the UI in watch mode
    dir: ui
    cmds:
      - npm run dev

  api:
    desc: Run the API in watch mode
    dir: api
    cmds:
      - watchexec --exts go -r task build:run:api

  package:
    desc: Build and package the application for the current platform
    cmds:
      - task: deps
      - task: build:release
      - task: archive
      - task: checksums

  package:all:
    desc: Build and package the application for all platforms
    cmds:
      - task: deps
      - task: build:release:all
      - task: archive:all
      - task: checksums

  build:release:
    desc: Build the release binary for GOOS and GOARCH (current platform by default)
    dir: api
    vars:
      DEFAULT_OUTPUT: "../dist/bin/{{.BINARY_NAME}}_{{.VERSION}}_{{ coalesce .GOOS OS }}_{{ coalesce .GOARCH ARCH }}{{ if eq (coalesce .GOOS OS) \"windows\" }}.exe{{ end }}"
      OUTPUT: "{{ coalesce .OUTPUT .DEFAULT_OUTPUT }}"
    generates:
      - "{{.OUTPUT}}"
    cmds:
      - |
        set -eou pipefail
        echo "build {{.OUTPUT}}"
        VERSION={{.VERSION}}
        COMMIT=$(git rev-parse HEAD)
        DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        BUILT_BY=$(whoami)
        LDFLAGS="-X main.version=$VERSION -X main.commit=$COMMIT -X main.date=$DATE -X main.builtBy=$BUILT_BY"
        GOOS={{.GOOS}} GOARCH={{.GOARCH}} CGO_ENABLED=0 go build \
          -ldflags "${LDFLAGS}" \
          -tags embedui \
          -o "{{.OUTPUT}}" \
          || echo "build failed for {{.OUTPUT}}"
    silent: true

  build:release:all:
    desc: Build the release binary for all supported platforms
    deps:
      - for:
          var: BUILD_OS_ARCH
          split: ","
        task: build:release
        vars:
          GOOS: "{{(.ITEM | split \"/\")._0}}"
          GOARCH: "{{(.ITEM | split \"/\")._1}}"

  archive:
    desc: Archive the release binary for GOOS and GOARCH (current platform by default)
    vars:
      INPUT: "dist/bin/{{.BINARY_NAME}}_{{.VERSION}}_{{ coalesce .GOOS OS }}_{{ coalesce .GOARCH ARCH }}{{ if eq (coalesce .GOOS OS) \"windows\" }}.exe{{ end }}"
      OUTPUT: "dist/archives/{{.BINARY_NAME}}_{{.VERSION}}_{{ coalesce .GOOS OS }}_{{ coalesce .GOARCH ARCH }}.zip"
    sources:
      - "{{.INPUT}}"
    generates:
      - "{{.OUTPUT}}"
    deps:
      - task: archive:dir
    cmds:
      - echo "archive {{.OUTPUT}}"
      - cd api && go run ./cmd/zip "../{{.OUTPUT}}" "../{{.INPUT}}"
    silent: true

  archive:all:
    desc: Archive all release binaries
    deps:
      - for:
          var: BUILD_OS_ARCH
          split: ","
        task: archive
        vars:
          GOOS: "{{(.ITEM | split \"/\")._0}}"
          GOARCH: "{{(.ITEM | split \"/\")._1}}"

  archive:dir:
    dir: dist/archives
    internal: true

  checksums:
    desc: Generate checksums for all archives
    cmds:
      - cd api && go build ./cmd/sha256 && cd ../dist/archives/ && ../../api/sha256 *.zip > checksums.txt

  test:
    desc: Run all go tests
    dir: api
    cmds:
      - go test -v -race -cover ./...

  docker:run:
    desc: Run the Docker container locally
    deps:
      - task: deps
    cmds:
      - docker compose up --build

  docker:
    desc: Build a Docker image with the latest git tag
    vars:
      TAGS: >-
        {{- if (regexMatch "^v[0-9]+\\.[0-9]+\\.[0-9]+$" .VERSION) }}
          {{- $versionParts := regexFindAll "[0-9]+" .VERSION 3 }}
          {{- $major := index $versionParts 0 }}
          {{- $minor := index $versionParts 1 }}
          {{- $patch := index $versionParts 2 }}
          -t {{.DOCKER_REPO}}:latest
          -t {{.DOCKER_REPO}}:v{{$major}}
          -t {{.DOCKER_REPO}}:v{{$major}}.{{$minor}}
          -t {{.DOCKER_REPO}}:v{{$major}}.{{$minor}}.{{$patch}}
        {{- else if (regexMatch "^v[0-9]+\\.[0-9]+\\.[0-9]+" .VERSION) }}
          -t {{.DOCKER_REPO}}:{{.VERSION}}
        {{- else }}
        {{- end }}
    preconditions:
      - sh: test -n "{{.TAGS}}"
        msg: "Git tag must be in the format vMAJOR.MINOR.PATCH* for docker build: {{.VERSION}}"
    cmds:
      - |
        VERSION={{.VERSION}}
        COMMIT=$(git rev-parse HEAD)
        DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        BUILT_BY=$(whoami)
        LDFLAGS="-X main.version=$VERSION -X main.commit=$COMMIT -X main.date=$DATE -X main.builtBy=$BUILT_BY"
        docker build --build-arg LDFLAGS="$LDFLAGS" {{.TAGS | replace "\n" " "}} -f Dockerfile {{.EXTRA_ARGS}} .

  docker:multiarch:
    desc: Build multi-architecture Docker images
    deps:
      - task: docker
        vars:
          EXTRA_ARGS: >-
            --platform {{ join "," .DOCKER_ARCH }}
            {{.EXTRA_ARGS}}
          DOCKER_REPO: "{{.DOCKER_REPO}}"

  docker:multiarch:push:
    desc: Build and push multi-architecture Docker images to GitHub Container Registry
    deps:
      - task: docker:multiarch
        vars:
          EXTRA_ARGS: >-
            --iidfile .docker-image-id
            --push {{ .DOCKER_ANNOTATIONS }}
          DOCKER_REPO: "{{.DOCKER_REPO}}"

  docker:multiarch:push:local:
    desc: Build and push multi-architecture Docker images to local registry
    preconditions:
      - sh: curl localhost:5000/v2/_catalog
        msg: "Local Docker registry is not running. Run 'docker compose up -d registry' to start it."
    cmds:
      - task: docker:multiarch:push
        vars:
          DOCKER_REPO: "{{.DOCKER_REPO_LOCAL}}"

  release:local:
    desc: Build, package, and create a local Docker image
    cmds:
      - task: deps
      - task: docker
        vars:
          EXTRA_ARGS: >-
            -t {{.DOCKER_REPO}}:latest

  release:local:multiarch:
    desc: Build and create a multi-architecture local Docker image
    cmds:
      - task: deps
      - task: docker:multiarch:push:local

  release:version:
    desc: Display the current version
    cmds:
      - echo {{ .VERSION }}
    silent: true
